FROM --platform=linux/amd64 pytorch/pytorch:2.9.1-cuda12.6-cudnn9-runtime AS hecktor2026-task

# Ensures that Python output to stdout/stderr is not buffered
ENV PYTHONUNBUFFERED=1

RUN groupadd -r user && useradd -m --no-log-init -r -g user user
USER user

WORKDIR /opt/app

COPY --chown=user:user requirements.txt /opt/app/

RUN python -m pip install \
    --user \
    --no-cache-dir \
    --no-color \
    --requirement /opt/app/requirements.txt

COPY --chown=user:user inference.py /opt/app/
COPY --chown=user:user segmentation.py /opt/app/
COPY --chown=user:user preprocessing.py /opt/app/
COPY --chown=user:user tn_staging.py /opt/app/
COPY --chown=user:user survival.py /opt/app/
COPY --chown=user:user feature_extraction.py /opt/app/
COPY --chown=user:user networks.py /opt/app/

ENTRYPOINT ["python", "inference.py"]
